name: curl_parser
description: Parse cURL command to Dart object and convert Dart object to cURL command.
version: 0.1.5-dev
homepage: https://github.com/foss42/apidash/tree/main/packages/curl_parser
repository: https://github.com/foss42/apidash/tree/main/packages/curl_parser
issue_tracker: https://github.com/foss42/apidash/issues
documentation: https://github.com/foss42/apidash/tree/main/packages/curl_parser

topics:
  - curl
  - api
  - rest
  - http
  - network

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  args: ^2.5.0
  json_annotation: ^4.11.0
  seed: any
  shlex: ^2.0.2

dev_dependencies:
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  lints: ^6.1.0
  test: ^1.30.0
