import 'package:insomnia/models/models.dart';

var collectionApiDashModel = InsomniaCollection(
  type: "export",
  exportDate: "2025-01-05T13:05:11.752Z",
  exportFormat: 4,
  exportSource: "insomnia.desktop.app:v10.3.0",
  resources: [
    Resource(
      id: "req_15f4d64ca3084a92a0680e29a958c9da",
      parentId: "fld_a2e9704c49034e36a05cdb3a233f6ebd",
      modified: 1736112258432,
      created: 1736111908438,
      url: "https://food-service-backend.onrender.com/api/users/",
      name: "get-with-params",
      description: "",
      method: "GET",
      body: Body(),
      parameters: [Parameter(
          id: "pair_bf0ae4f4280e440a8a591b64fd4ec4f4",
          name: "user_id",
          value: "34",
          description: "",
          disabled: false,
        )
      ],
      headers: [
        Header(
          name: "User-Agent",
          value: "insomnia/10.3.0",
        )
      ],
      metaSortKey: -1736111908438,
      isPrivate: false,
      afterResponseScript: null,
      settingSendCookies: true,
      settingStoreCookies: true,
      settingDisableRenderRequestBody: false,
      settingEncodeUrl: true,
      settingRebuildPath: true,
      settingFollowRedirects: "global",
      type: "request",
    ),
    Resource(
      id: "req_db3c393084f14369bb409afe857e390c",
      parentId: "fld_a2e9704c49034e36a05cdb3a233f6ebd",
      modified: 1736082089077,
      created: 1736082089077,
      url: "https://api.apidash.dev/country/codes",
      name: "test-get",
      description: "",
      method: "GET",
      body: Body(),
      parameters: [],
      headers: [],
      preRequestScript: "",
      metaSortKey: -1736082080558,
      isPrivate: false,
      afterResponseScript: "",
      settingSendCookies: true,
      settingStoreCookies: true,
      settingDisableRenderRequestBody: false,
      settingEncodeUrl: true,
      settingRebuildPath: true,
      settingFollowRedirects: "global",
      type: "request",
    ),
    Resource(
      id: "req_ba718bbacd094e95a30ef3f07baa4e42",
      parentId: "fld_a2e9704c49034e36a05cdb3a233f6ebd",
      modified: 1736082089078,
      created: 1736082089078,
      url: "https://api.apidash.dev/case/lower",
      name: "test-post",
      description: "",
      method: "POST",
      body: Body(
        mimeType: "application/json",
        text: "{\n  \"text\": \"Grass is green\"\n}",
      ),
      parameters: [],
      headers: [
        Header(
          name: "Content-Type",
          value: "application/json",
        )
      ],
      preRequestScript: "",
      metaSortKey: -1736082080557,
      isPrivate: false,
      afterResponseScript: "",
      settingSendCookies: true,
      settingStoreCookies: true,
      settingDisableRenderRequestBody: false,
      settingEncodeUrl: true,
      settingRebuildPath: true,
      settingFollowRedirects: "global",
      type: "request",
    ),
    Resource(
      id: "req_24cff90fc3c74e71a567f61d3f8e8cc1",
      parentId: "fld_a2e9704c49034e36a05cdb3a233f6ebd",
      modified: 1736082089078,
      created: 1736082089078,
      url: "https://reqres.in/api/users/2",
      name: "test-put",
      description: "",
      method: "PUT",
      body: Body(
        mimeType: "application/json",
        text: "{\n    \"name\": \"morpheus\",\n    \"job\": \"zion resident\"\n}"
      ),
      parameters: [],
      headers: [
        Header(
          name: "Content-Type",
          value: "application/json",
        )
      ],
      preRequestScript: "",
      metaSortKey: -1736082080556,
      isPrivate: false,
      afterResponseScript: "",
      settingSendCookies: true,
      settingStoreCookies: true,
      settingDisableRenderRequestBody: false,
      settingEncodeUrl: true,
      settingRebuildPath: true,
      settingFollowRedirects: "global",
      type: "request",
    ),
  ]
);
