# GSOC Proposal for DashBot

## About Me  
**Full Name:** Mrudul Killedar 
**Email:** mrudulkilledar111@gmail.com 
**Phone:** +91 7489685683  
**Discord Handle:** Mrudul  
**GitHub Profile:** https://github.com/Mrudul111  
**LinkedIn:** www.linkedin.com/in/mrudul-killedar-5b0121245  
**Time Zone:** GMT + 5:30  
**Resume:** https://drive.google.com/file/d/1ICvI5h8FP5cTtMIvQcu918Adc5JP1DQb/view?usp=share_link  

## University Information  
**University Name:** Vellore Institute of Technology   
**Program:** B.Tech in Computer Science Engineering  
**Year:** 2025  
**Expected Graduation Date:** July 2025

## Motivation & Past Experience  
**1. Have you worked on or contributed to a FOSS project before?**  
Yes, I have contributed to FOSS project ie APIDash:  
- Solves Beautify JSON and Highlight JSOn - https://github.com/foss42/apidash/pull/595  
- Share button functionality - https://github.com/foss42/apidash/pull/571#event-16324056931 
- Homebrew Installation Guide - https://github.com/foss42/apidash/pull/566#event-16282262849
- Multiple-Model in DashBot - https://github.com/foss42/apidash/pull/704

**2. What is your one project/achievement that you are most proud of? Why?**  
I am most proud of 2 projects particularly one is Parking24 which is an app that was made to solve parking problems of UAE market and i was assigned this project in my internship at Wisho (Now called Hyve AI Labs).
I am proud of the project because it is adding real world value and solving a very real problem. Also i have been working on a Machine learning model that is to predict cybersickness using SNN and currently we are achieving accuracy of 87.234% which is better than existing model that has accuracy of 76.11% and we achieved this because of our better approach for data cleaning. 

**3. What kind of problems or challenges motivate you the most to solve them?**  
I am most motivated by solving complex problems that challenge me to think in new ways and push my boundaries. I enjoy tackling problems that I have never encountered before, as they provide an opportunity to learn, explore innovative solutions, and develop a deeper understanding of different technologies. The thrill of breaking down a difficult problem, analyzing it from different angles, and coming up with an effective solution is what drives me the most.

**4. Will you be working on GSoC full-time?**  
Yes, I will be working full-time on my GSoC project.  

**5. Do you mind regularly syncing up with the project mentors?**  
Not at all! I am happy to have regular sync-ups with my mentors to ensure smooth progress and alignment with project goals.  

**6. What interests you the most about API Dash?**  
API Dash is an innovative tool that simplifies API testing and monitoring. I personally felt other apps are very bloated and performace is really clunky on the other hand API Dash is really smooth, looks aesthetically pleasing and use of AI just seperates them from rest of the API Testing Platform. I have personally shifted to API Dash for my backend testing. I would love to contribute to API Dash because i feel this is a project that is adding such a great value to developer community.

**7. Can you mention some areas where the project can be improved?**  
Some areas where API Dash can be improved include:  
- **UI for DashBot:** The UI currently is very basic and lacks a professional approach.
- **Responses:** The response that is generated by clicking the buttons is on-point but the bot is not conversational enough.


## Project Proposal Information  
### **Proposal Title:** DashBot 

### **Abstract**  
DashBot is an AI-powered assistant designed to supercharge developer productivity within API Dash by automating repetitive tasks, improving API debugging, and providing intelligent recommendations. By leveraging advanced large language models (LLMs), DashBot enables developers to interact with APIs using natural language, making API testing, debugging, documentation, and integration significantly more efficient and intuitive.

### **Detailed Description**  
DashBot is designed to be an AI-powered assistant for API Dash that helps developers automate tedious tasks, follow best practices, and obtain contextual suggestions via natural-language input. This project extends its capabilities by adding the following advanced features:  

#### **1. AI-Powered Code Error Detection & Auto-Fix**  
- Detect syntax and logical errors in API requests and integration code.  
- Provide human-readable explanations and suggest one-click fixes.  
- Ensure best practices in authentication, rate limiting, and error handling.  
- **Flutter Packages:** [`dart_code_metrics`](https://pub.dev/packages/dart_code_metrics), [`lsp_dart`](https://pub.dev/packages/lsp_dart), [`openai_dart`](https://pub.dev/packages/openai_dart)  

#### **2. Multi-Model Support & Fine-Tuning**  
- Enable users to switch between different LLMs (GPT, Llama, Claude, Gemini, etc.).  
- Provide on-device LLM support for private inference.  
- Allow user-defined prompt fine-tuning for personalized suggestions.  
- **Flutter Packages:** [`ollama_flutter`](https://pub.dev/packages/ollama_flutter), [`tflite_flutter`](https://pub.dev/packages/tflite_flutter), [`http`](https://pub.dev/packages/http)  

#### **3. Multi-Language API Code Generation & AI-Powered Auto Refactoring**  
- Extend API code generation to Kotlin, Swift, Go, and Rust.  
- Auto-refactor generated code for better maintainability and efficiency.  
- Provide real-time code quality analysis and performance suggestions.  
- **Flutter Packages:** [`dart_style`](https://pub.dev/packages/dart_style), [`flutter_highlight`](https://pub.dev/packages/flutter_highlight), [`language_server_protocol`](https://pub.dev/packages/language_server_protocol)  

#### **4. AI-Driven API Contract Testing & Schema Validation**  
- Auto-detect API schema inconsistencies with OpenAPI, GraphQL, JSON Schema.  
- Flag breaking changes and provide regression testing for API updates.  
- Generate mock API contracts for frontend and backend teams.  
- **Flutter Packages:** [`json_schema`](https://pub.dev/packages/json_schema), [`dio`](https://pub.dev/packages/dio), [`openapi_parser`](https://pub.dev/packages/openapi_parser)  

#### **5. AI-Powered API Performance & Load Testing**  
- Predict API performance bottlenecks and optimize response times.  
- Simulate real-world API traffic patterns for scalability testing.  
- Suggest optimal rate limits and caching strategies based on usage trends.  
- **Flutter Packages:** [`flutter_jmeter`](https://pub.dev/packages/flutter_jmeter), [`isolate`](https://pub.dev/packages/isolate), [`statsfl`](https://pub.dev/packages/statsfl)  

#### **6. AI-Assisted API Integration Testing Across Platforms**  
- Auto-generate end-to-end API tests for **Flutter, React, Next.js, etc.**  
- Ensure consistent API behavior across web and mobile applications.  
- Test authentication workflows, session handling, and cross-platform API interactions.  
- Provide real-time debugging assistance inside development environments.  
- **Flutter Packages:** [`integration_test`](https://pub.dev/packages/integration_test), [`mockito`](https://pub.dev/packages/mockito), [`flutter_test`](https://api.flutter.dev/flutter/flutter_test/flutter_test-library.html)

### **Weekly Timeline**  

| **Week** | **Task** |  
|----------|---------|  
| Week 1  | Implement AI-powered test case generation for API requests |  
| Week 2  | Develop initial integration with API Dash and set up AI-based testing modules |  
| Week 3  | Conduct testing, refine AI model responses, and improve performance |  
| Week 4  | Implement intelligent API documentation generation with auto-explanations |  
| Week 5  | Enhance UI/UX for generated documentation, including markdown formatting and syntax highlighting |  
| Week 6  | Gather user feedback, refine documentation AI, and introduce auto-refactoring for better maintainability |  
| Week 7  | Implement AI-driven response visualization, including charts and statistical insights |  
| Week 8  | Integrate debugging assistance, including error detection and auto-fixes for API requests |  
| Week 9  | Improve UI elements, streamline workflows, and optimize model performance for faster processing |  
| Week 10 | Conduct final testing, polish features, and document best practices for AI-based API automation |  

---  
