// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bytes_to_string`, `escape_json`, `json_value_to_string`, `template_to_string`

/// Parses a Hurl file content and returns a simplified JSON representation
/// containing just the HTTP requests
String parseHurlToJson({required String content}) =>
    RustLib.instance.api.crateApiHurlParserParseHurlToJson(content: content);
