include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: ignore
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"

linter:
  rules:
