include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "doc/*"

linter:
  rules:

plugins:
  riverpod_lint: ^3.1.4
