name: apidash_mcp
description: MCP server package for API Dash.
version: 1.0.0

environment:
  sdk: ^3.11.3

resolution: workspace

# Add regular dependencies here.
dependencies:
  mcp_dart: ^2.1.0
  path: ^1.9.0

  apidash_storage:
    path: ../apidash_storage

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
