name: "Code Analysis"
on: [ push ]


jobs:
  Flutter-Analyze:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Get Flutter Env
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter --version

    - name: Code Analysis
      run: |
        flutter pub get
        flutter analyze
