name: Semgrep

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: semgrep-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: returntocorp/semgrep-action@v1
        # or: docker run semgrep/semgrep semgrep scan --config auto --sarif -o semgrep.sarif
        with:
          config: p/security-audit
          generateSarif: "1"

      - uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
