name: Unit Tests

on:
  pull_request:
  push:

jobs:
  tests:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        flutter-version: ["3.16.9", "3.x"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version}}
          channel: stable
          cache: true
      - run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
      # TODO add a codecov account and register token in secrets
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: coverage/lcov.info
